name: Continuous Integration Tests

on:
  pull_request:
    branches: [ main ]

jobs:

  ci_test:
    name: Clickhouse CI
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:23.3
        ports:
          - 9000:9000
          - 8123:8123
    container:
      image: ghcr.io/a-poliakov/dbt_clickhouse_lab:ci
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello world!"
      - run: dbt --version
      - run: dbt debug --target ci
      - run: dbt deps --target ci
      - run: dbt run-operation init_s3_sources --target ci
      - run: dbt build --target ci
