name: Continuous Integration Tests

on:
  pull_request:
    branches: [ main ]

jobs:

  ci_test:
    name: Clickhouse CI
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:23.3
        ports:
          - 9000:9000
          - 8123:8123
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello world!"
